misPerris/misPerris/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('perris.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url('', include('pwa.urls')),

]

misPerris/perris/urls.py
from django.conf.urls import include,url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers

app_name = 'perris'


router = routers.DefaultRouter()
router.register(r'perro',views.PerroViewSet)

urlpatterns = [
    url(r'^$', views.Home),
    url(r'^in', views.Home2),
    url(r'^registro',views.Contacto),
    url(r'^login',views.Login.as_view()),
    url(r'^cerrar-sesion/$',views.SignOutView.as_view(), name='cerrar_sesion'),
    url(r'^errorpermisos',views.errorPermisos),
    url(r'^servicios',views.menu),
    url(r'^subir',views.subir),
    url(r'^perros', views.listaPerro, name='list'),
    url(r'^(?P<pk>\d+)$', views.detallesPerro.as_view(), name='detail'),
    url(r'^editar/(?P<pk>\d+)$', views.editarPerro.as_view(), name='edit'),
    url(r'^borrar/(?P<pk>\d+)$', views.borrarPerro.as_view(), name='delete'),
    url(r'^api/',include(router.urls)),
    url(r'base',views.base)
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misPerris/perris/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
# Create your models here.


class usuario (models.Model):
    user = models.OneToOneField(User,on_delete = "models.CASCADE")
    run = models.CharField( primary_key = True, max_length = 10)
    nombre = models.CharField(max_length = 150)
    fNacimiento = models.DateField()
    fono = models.IntegerField()
    region = models.CharField(max_length = 50)
    ciudad = models.CharField(max_length = 50)
    tipoVivienda = models.CharField(max_length = 100)

    def __str__(self):
        return self.user.username + ' ~ ' + self.run
    


class perro(models.Model):
    foto = models.ImageField(upload_to="perros", height_field=None, width_field=None, max_length=None)
    nombre = models.CharField(max_length = 150)
    raza = models.CharField(max_length = 150)
    descripcion = models.CharField(max_length = 300)
    estados = (
        ('R','Rescatado'),
        ('D','Disponible'),
        ('A','Adoptado')
    )
    estado = models.CharField(max_length=1,choices = estados)

    def __str__(self):
        return self.nombre +' ~ '+ self.raza + ' ~ ' + self.estado
    


    

misPerris/perris/forms.py
from django import forms
from .models import usuario,perro
from django.contrib.auth.models import User

class PerfilForm(forms.ModelForm):

    class Meta:
        model = usuario
        fields = ('run','nombre','fNacimiento','fono','region','ciudad','tipoVivienda')

class perroForm(forms.ModelForm):
    class Meta:
        model = perro
        fields = ('foto','nombre','raza','descripcion','estado')



class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('username','password','email')




class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())

misPerris/perris/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.contrib.auth.forms import AuthenticationForm
from django.http.response import HttpResponseRedirect
from django.contrib.auth import login,authenticate
from .forms import PerfilForm,UserForm,LoginForm,perroForm
from django.contrib.auth.models import User
from django.views.generic.edit import FormView,DeleteView,UpdateView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.contrib.auth.hashers import *
from django.contrib.auth.models import Group
from django.core.cache import cache
from django.contrib import messages
from django.contrib.auth.decorators import login_required,user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth.views import LoginView,LogoutView
from .models import perro
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import viewsets
from .serializers import PerrosSerializer

# Create your views here.
grupo = None
def Home(request):
    return render(request,'perris/index.html',{})
@login_required(login_url='login.html')
def Home2(request):
    return render(request,'perris/index2.html',{})

def base(request):
    return render(request,'perris/base.html')


def errorPermisos(request):
    return render(request,'perris/errorpermisos.html')

#VISTA PARA FORMULARIO CONTACTO
def Contacto(request):
    if request.method == "POST":
        profileForm = PerfilForm(request.POST)
        usuarioForm = UserForm(request.POST)

        if profileForm.is_valid() and usuarioForm.is_valid():
            user = usuarioForm.save(commit=False)
            clave_virgen = usuarioForm.cleaned_data['password']
            clave_encriptada = make_password(clave_virgen,None,'md5')
            user.set_password(clave_encriptada)
            user.save() 
            user.groups.add(Group.objects.get(name='usuario_promedio'))
            instancia = profileForm.save(commit=False)
            instancia.user_id = User.objects.latest('id').id
            instancia.save()
           
        else:
            print(profileForm.errors)
            print(usuarioForm.errors)
    else:
        profileForm = PerfilForm()
        usuarioForm = UserForm()
    return render(request,'perris/form.html',{'form': profileForm})


class Login(LoginView):
        template_name = 'perris/login.html'



def superuser_or_moderador(user):
    return user.is_superuser or user.groups.filter(name='moderador').exists()



@login_required(login_url='login.html')
@user_passes_test(superuser_or_moderador,login_url='/errorpermisos')
def subir(request):
    if request.method == "POST":
        print("post")
        form = perroForm(request.POST,request.FILES,request.user)
        print(form.errors)
        if form.is_valid():
            print("valido")
            form.save()
    return render(request,'perris/upload.html',{'form': perroForm})

@login_required(login_url='login.html')
def menu(request):
    if request.user.groups.filter(name='moderador').exists():
        return render(request,'perris/menuModerador.html',{})
    else:
        return render(request,'perris/menuNormal.html',{})

@login_required(login_url='login.html')
def listaPerro(request):
    todos = perro.objects.all()
    disponibles = perro.objects.filter(estado = 'D')
    return render(request,'perris/perro_list.html',{'todos':todos,'disponibles':disponibles})




class detallesPerro(DetailView):
    model = perro
    @method_decorator(login_required(login_url='/login.html'))
    def dispatch(self, *args, **kwargs):
        return super(detallesPerro, self).dispatch(*args, **kwargs)


class editarPerro(UpdateView,LoginRequiredMixin):
    model = perro
    success_url = reverse_lazy('perris:list')
    fields = ('foto','nombre','raza','descripcion','estado')
    login_url = 'login.html'
    @method_decorator(login_required(login_url='/login.html'))
    @method_decorator(user_passes_test(superuser_or_moderador,login_url='/errorpermisos'))
    def dispatch(self, *args, **kwargs):
        return super(editarPerro, self).dispatch(*args, **kwargs)


class borrarPerro(DeleteView,LoginRequiredMixin):
    model = perro
    success_url = reverse_lazy('perris:list')
    login_url = 'login.html'
    @method_decorator(login_required(login_url='/login.html'))
    @method_decorator(user_passes_test(superuser_or_moderador,login_url='/errorpermisos'))
    def dispatch(self, *args, **kwargs):
        return super(borrarPerro, self).dispatch(*args, **kwargs)


class SignOutView(LogoutView):
    pass



class PerroViewSet(viewsets.ModelViewSet):
    queryset = perro.objects.filter(estado = 'D')
    serializer_class = PerrosSerializer
    

misPerris/perris/templates/perris/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
    {% load static %}
{% load pwa %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'misPerris/css/style.css' %}">
        {% progressive_web_app_meta %}
        <title>Mis Perris</title>
    </head>
    <body>
        <header>
            <img src="{% static 'misPerris/img/logo.png' %}" alt="logo">
            <nav id="menu-principal">
                <ul>
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Quienes Somos</a></li>
                    <li><a href="servicios">Servicios</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="cerrar-sesion?next=/">Cerrar Sesión</a></li>
                    {% else %}
                        <li><a href="registro">Regístrate</a></li>
                        <li><a href="login">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div id="contenedor-central">

            {% block content %}

		    {% endblock %}
        </div>

        <footer>
            <p>Desarrollo Web y Mobile</p>
        </footer>
    </body>
</html>

misPerris/perris/templates/perris/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    aa
</body>
</html>

misPerris/perris/templates/perris/doginfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/info.css">
    <title>¡Adóptame!</title>
</head>
<body>
    <div id="contenedor">
    <h1>Adóptame</h1>
    <section id="presentacion">
    <div id="textos">
    <p id="presentación">Mi nombre es: Lorem Ipsum</p>
    <p id="descripcion">Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
        quis nostrud exercitation ullamco 
        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit </p>
    </div>
    <img src="img/Pexel_tn.jpg" alt="">
    </section>
</div>
</body>
</html>

misPerris/perris/templates/perris/errorLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <title>Error</title>
</head>
<body class="container">
    <h1 class="col-md-12">No dispones de los permisos necesarios para acceder a este modulo del sistema</h1>
</body>
</html>

misPerris/perris/templates/perris/errorpermisos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error permisos</title>
</head>
<body>
    <h3>Lo sentimos, no dispones de los permisos necesarios para acceder a este módulo del sistema</h3>
</body>
</html>

misPerris/perris/templates/perris/form.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Regístrate en Mis Perris</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{% static 'misPerris/css/estilo.css' %}">
    
    <link rel="stylesheet" href="{% static 'misPerris/css/animate.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js"></script>
    <script src="{% static 'misPerris/js/validarRUT.js' %}"></script>    
    <script src="{% static 'misPerris/js/regionesComunas.js' %}"></script>
    <script src="{% static 'misPerris/js/validacion.js' %}"></script>
</head>
<body>
    <header>
        <div class="container">
            <h1>Formulario de registro</h1>
        </div>
    </header>
    <div class="container-fluid main">
        <form id="form" method="POST" class="form-horizontal">{% csrf_token %}
            <br>
            <div class="form-group">
                <label class="control-label col-md-2" for="correo">Correo:</label>
                <div class="col-md-10">
                    <input class="form-control" type="email" name = "correo" required placeholder="hola@gmail.com" id="correo">
                </div>                
            </div>            
            
            <div class="form-group">
                <label class="control-label col-md-2" for="rut">Rut</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="rut" name="run" required maxlength="10" oninput="checkRut(this)" placeholder="12345678-K">
                </div>        
            </div>


            <div class="form-group">
                <label class="control-label col-md-2" for="password">Usuario</label>
                <div class="col-md-10">
                    <input class="form-control" requiered type="text" id="password" name="username">
                </div>        
            </div>



            <div class="form-group">
                <label class="control-label col-md-2" for="password">Contraseña</label>
                <div class="col-md-10">
                    <input class="form-control" requiered type="password" id="password" name="password">
                </div>        
            </div>


            <div class="form-group">
                <label class="control-label col-md-2" for="nombre">Nombre Completo:</label>
                <div class="col-md-10">
                    <input class="form-control" required pattern="[A-Za-z ]+" placeholder="Francisco Javier Echenique Lisperguer" type="text"
                     name= "nombre" id="nombre">
                </div>                
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Fecha de Nacimiento:</label>
                <div class="col-md-10">
                    <input class="form-control" required type="date" max="2000-12-31" name="fNacimiento" id="fechaNacimiento">
                </div>                
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="telefono">Telefono</label>
                <div class="col-md-10">
                    <input class="form-control" required placeholder="987654321" type="tel" pattern="[0-9]{9}" name="fono" id="telefono">
                </div>                
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="regiones">Región:</label>
                <div class="col-md-10">
                    <select class="form-control" name = "region" id="regiones"></select>
                </div>                
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Ciudad:</label>
                <div class="col-md-10">
                    <select class="form-control" name = "ciudad" id="comunas"></select>
                </div>                
            </div>      
            
            <div class="form-group">
                <label class="control-label col-md-2">Tipo de Vivienda</label>
                <div class="col-md-10">
                    <select name = "tipoVivienda" class="form-control" id="opcion">
                        <option value="Casa con patio grande">Casa con patio grande</option>
                        <option value="Casa con patio pequeño">Casa con patio pequeño</option>
                        <option value="Casa sin patio">Casa sin patio</option>
                        <option value="Departamento">Departamento</option>                
                    </select>
                </div>                
            </div>

            <div class="form-group">
                <div class="col-md-2 col-md-offset-2">
                    <button type="submit" class="btn btn-primary color">Enviar</button>
                </div>
            </div>
        </form>
    </div>
    <footer>
        <div class="container" id="uno"> 
            <img class="img-responsive" src="{% static 'misPerris/img/perro.png' %}" alt="">
        </div>
    </footer>
</body>
</html>

misPerris/perris/templates/perris/login.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<!-- saved from url=(0047)http://localhost:8000/admin/login/?next=/admin/ -->
<html lang="en-us"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Log in | Django site admin</title>
<link rel="stylesheet" type="text/css" href="{% static 'misPerris/css/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'misPerris/css/login.css'%}">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'misPerris/css/responsive.css' %}">
<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=" login" data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="http://localhost:8000/login/">Login Mis Perris :)</a></h1>

        </div>
        
        
    </div>
    <!-- END Header -->
    
    

    
        
    

    <!-- Content -->
    <div id="content" class="colM">
        
        
        




<div id="content-main">


<form  method="POST" id="login-form"><input type="hidden" name="" value="">
  {% csrf_token %}
  <div class="form-row">
    
    <label class="required" for="id_username">Usuario:</label> 
     <input type="text" id="id_username" name="username">
  </div>
  <div class="form-row">
    
    <label class="required" for="id_password">Clave:</label>
     <input type="password" id="id_password" name="password">
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Iniciar Sesión">
  </div>
  <a class="btn btn-primary btn-block" href="{% provider_login_url "facebook" method="oauth2" %}">
   <span class="fab fa-facebook"></span>
      Iniciar con Facebook
 </a>
</form>

{% block content %}

    {% if form.errors %}
        <p>Usuario o contraseña incorrecta</p>
    {% endif %}

{% endblock %}

</div>

        
        <br class="clear">
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->



</body></html>

misPerris/perris/templates/perris/menuNormal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'misPerris/css/baseUsers.css' %}">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>Panel Usuario</title>
</head>
<body>
    <header class="container">
            <nav class="navbar navbar-default">
                    <div class="container-fluid">
                      <!-- Brand and toggle get grouped for better mobile display -->
                      <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Menú Mis Perris ~ Usuarios</a>
                      </div>
                  
                      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><a href="/in">Salir</a></li>
                            <li><a href="/perros">Mascotas disponibles</a></li>
                          </ul>
                      </div>

                    </div>
                  </nav>
    </header>
</body>
</html>

misPerris/perris/templates/perris/perro_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
            <!-- Latest compiled and minified CSS -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

            <!-- Latest compiled and minified JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
            
            <link rel="stylesheet" href="{% static 'misPerris/css/estilo.css' %}">
            <link rel="stylesheet" href="{% static 'misPerris/css/animate.css' %}">
        
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js"></script>
            <script src="{% static 'js/validacion.js' %}"></script>
</head>
<body>
        <header>
                <div class="container">
                    <img src="{% static 'misPerris/img/logo.png' %}" alt="logo" class="col-md-6">
                    <h1 class="col-md-5 col-md-offset-1">Detalles Rescatado</h1>
                </div>
            </header>
    <div class="container-fluid main">
            <h1>{{ perro.nombre }}</h1>
            <img  class="img-responsive col-md-6 .col-md-offset-3" src="media/{{ perro.foto }}" alt="">
            <h3>Raza: <i>{{ perro.raza }}</i></h3>
            <h3>Descripcion: <i>{{ perro.descripcion }}</i></h3>
            <h3>Estado: <i>{{ perro.get_estado_display }}</i></h3>
            <h3>
                <a href="{% url "perris:list" %}">Regresar</a>
            </h3>
    </div>
</body>
</html>

misPerris/perris/templates/perris/perro_list.html
{% load static %}
{% load my_templatetag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lista de perros</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        
        <link rel="stylesheet" href="{% static 'misPerris/css/estilo.css' %}">
        <link rel="stylesheet" href="{% static 'misPerris/css/animate.css' %}">
    
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js"></script>
        <script src="{% static 'js/validacion.js' %}"></script>
</head>
<body>    
    <header>
                <a class = "btn btn-secondary btn-lg" href="/servicios">Regresar</a>
        <div class="container">
            <img src="{% static 'misPerris/img/logo.png' %}" alt="logo" class="col-md-6">
            {% if request.user|has_group:"moderador" %}
            <h1 class="col-md-5 col-md-offset-1">Lista de perros</h1>
            {% else %}
            <h1 class="col-md-5 col-md-offset-1">Lista de perros disponibles</h1>
            {% endif %}
        </div>
    </header>
    <div class="container-fluid main">
    {% if request.user|has_group:"moderador" %}
            <ul>
                    {% for perro in todos %}
                        <li>
                            <h3>Nombre mascota: {{ perro.nombre }}</h3>
                            <a href="{% url "perris:detail" perro.id %}">Ver</a>
                            <a href="{% url "perris:edit" perro.id %}">Editar</a>
                            <a href="{% url "perris:delete" perro.id %}">Borrar</a>
                        </li>
                    {% endfor %}
                </ul>
    {% else %}
        <ul>
            {% for perro in disponibles %}
        <li>
            <p>Nombre mascota: {{ perro.nombre }}</p>
            <a href="#">Adoptar</a>
        </li>
    {% endfor %}
        </ul>
    {% endif %}

    </div>
   
</body>
<footer>
        <div class="container" id="uno"> 
            <img class="img-responsive" src="{% static 'misPerris/img/perro.png' %}" alt="">
        </div>
</footer>
</html>